import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { createApp } from '../server/app.js';
const dir=mkdtempSync(path.join(tmpdir(),'nutq-test-'));
const filename=path.join(dir,'test.sqlite');
let instance,server,base;
async function start(){instance=createApp({filename,teamMode:true});server=instance.app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));base='http://127.0.0.1:'+server.address().port;}
async function stop(){await new Promise(r=>server.close(r));instance.db.close();}
before(start);after(async()=>{await stop();rmSync(dir,{recursive:true});});
async function request(route,{method='GET',body,cookie,csrf=true,revision}={}){let version=revision;if(route==='/me'&&method==='PATCH'&&version===undefined)version=(await request('/me',{cookie})).body.user?.revision;if(version===undefined&&['PUT','DELETE'].includes(method)){const table=route.split('/')[1],id=route.split('/')[2];const rows=await request('/'+table,{cookie});version=Array.isArray(rows.body)?rows.body.find(r=>r.id===id)?.revision:undefined;}const r=await fetch(base+'/api'+route,{method,headers:{'Content-Type':'application/json',...(version!==undefined?{'If-Match':String(version)}:{}),...(csrf?{'X-Requested-With':'Nutq'}:{}),...(cookie?{Cookie:cookie}:{})},body:body?JSON.stringify(body):undefined});return {status:r.status,body:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0],headers:r.headers};}
const person={name:'Test Bemor',birth_date:'2020-02-29',guardian:'Test Vasiy',phone:'+998901234567',focus:'R tovushi',notes:'Tekshiruv',status:'active'};
test('Account isolation, validation, schedule conflicts, persistence, export and session revocation',async()=>{
  assert.equal((await request('/patients')).status,401);
  assert.equal((await request('/auth/register',{method:'POST',body:{name:'A',email:'a@example.com',password:'testpassword123'},csrf:false})).status,403);
  const a=await request('/auth/register',{method:'POST',body:{name:'Aziza',email:'a@example.com',password:'testpassword123'}});
  assert.equal(a.status,200);assert.ok(a.headers.get('set-cookie').includes('HttpOnly'));assert.ok(a.headers.get('set-cookie').includes('SameSite=Strict'));assert.equal(a.body.user.password,undefined);
  const b=await request('/auth/register',{method:'POST',body:{name:'Zarina',email:'b@example.com',password:'testpassword123'}});
  const cookie=a.cookie;
  const p=await request('/patients',{method:'POST',cookie,body:person});assert.equal(p.status,201);
  assert.equal((await request('/patients',{method:'POST',cookie,body:{...person,birth_date:'2020-02-30'}})).status,400);
  assert.equal((await request('/patients',{method:'POST',cookie,body:{...person,birth_date:'2099-01-01'}})).status,400);
  assert.equal((await request('/patients',{cookie:b.cookie})).body.length,0);
  assert.equal((await request('/patients/'+p.body.id,{method:'DELETE',cookie:b.cookie})).status,404);
  assert.equal((await request('/patients/'+p.body.id,{method:'PUT',cookie:b.cookie,body:person})).status,404);
  const ex=await request('/exercises',{method:'POST',cookie,body:{title:'Test mashq',category:'Talaffuz',duration:10,instructions:'Test tartibi'}});assert.equal(ex.status,201);
  const appointment={patient_id:p.body.id,date:'2026-09-15',time:'09:00',duration:45,title:'Test qabul',status:'scheduled',notes:''};
  assert.equal((await request('/appointments',{method:'POST',cookie:b.cookie,body:appointment})).status,404);
  const ap=await request('/appointments',{method:'POST',cookie,body:appointment});assert.equal(ap.status,201);
  assert.equal((await request('/appointments',{method:'POST',cookie,body:{...appointment,time:'09:30'}})).status,409);
  assert.equal((await request('/appointments',{method:'POST',cookie,body:{...appointment,time:'23:50'}})).status,400);
  const adjacent=await request('/appointments',{method:'POST',cookie,body:{...appointment,time:'09:45'}});assert.equal(adjacent.status,201);
  assert.equal((await request('/appointments/'+ap.body.id,{method:'PUT',cookie,body:{...appointment,status:'completed'}})).status,200);
  assert.equal((await request('/appointments/'+adjacent.body.id,{method:'PUT',cookie,body:{...appointment,time:'09:30'}})).status,409);
  assert.equal((await request('/appointments/'+ap.body.id,{method:'PUT',cookie,body:{...appointment,status:'cancelled'}})).status,200);
  assert.equal((await request('/appointments',{method:'POST',cookie,body:{...appointment,time:'09:00'}})).status,201);
  const result={patient_id:p.body.id,exercise_id:ex.body.id,date:'2026-09-15',score:72,notes:'Yaxshilandi'};
  assert.equal((await request('/results',{method:'POST',cookie,body:{...result,score:101}})).status,400);
  assert.equal((await request('/results',{method:'POST',cookie:b.cookie,body:result})).status,404);
  assert.equal((await request('/results',{method:'POST',cookie,body:result})).status,201);
  await stop();await start();
  assert.equal((await request('/results',{cookie})).body[0].score,72);
  assert.equal((await request('/patients',{cookie})).body[0].name,'Test Bemor');
  const backup=await request('/export',{cookie});assert.equal(backup.body.patients.length,1);assert.equal(backup.body.profile.password,undefined);assert.equal(backup.body.sessions,undefined);assert.equal(backup.body.results.length,1);
  const backupB=await request('/export',{cookie:b.cookie});assert.equal(backupB.body.patients.length,0);
  const login=await request('/auth/login',{method:'POST',body:{email:'a@example.com',password:'testpassword123'}});assert.equal(login.status,200);
  assert.equal((await request('/password',{method:'POST',cookie,body:{current:'testpassword123',password:'newpassword123'}})).status,200);
  assert.equal((await request('/me',{cookie:login.cookie})).status,401);
  assert.equal((await request('/auth/login',{method:'POST',body:{email:'a@example.com',password:'testpassword123'}})).status,401);
  assert.equal((await request('/exercises/'+ex.body.id,{method:'DELETE',cookie})).status,200);
  assert.equal((await request('/results',{cookie})).body[0].exercise_id,null);
  assert.equal((await request('/patients/'+p.body.id,{method:'DELETE',cookie})).status,409);
  assert.equal((await request('/patients/'+p.body.id,{method:'PUT',cookie,body:{...person,status:'archived'}})).status,200);
  assert.equal((await request('/results',{cookie})).body.length,1);
  assert.ok((await request('/appointments',{cookie})).body.length>0);
  await request('/logout',{method:'POST',cookie});assert.equal((await request('/me',{cookie})).status,401);
});
test('Demo data is isolated per session',async()=>{const a=await request('/auth/demo',{method:'POST'}),b=await request('/auth/demo',{method:'POST'});assert.equal(a.body.user.demo,true);assert.notEqual(a.body.user.id,b.body.user.id);const p=await request('/patients',{cookie:a.cookie}),q=await request('/patients',{cookie:b.cookie});assert.equal(p.body.length,4);assert.notEqual(p.body[0].id,q.body[0].id);});
test('Profile customization persists, supports partial updates and stays private',async()=>{
  const a=await request('/auth/demo',{method:'POST'}),b=await request('/auth/demo',{method:'POST'});
  const changes={name:'Malika Salimova',clinic:'Rivoj markazi',specialty:'Logoped-defektolog',phone:'+998901234567',address:'Toshkent',bio:'Bolalar nutqi bilan ishlayman.',experience_years:7,accent:'blue',avatar:''};
  const updated=await request('/me',{method:'PATCH',cookie:a.cookie,body:changes});assert.equal(updated.status,200);
  for(const [key,value] of Object.entries(changes))assert.equal(updated.body.user[key],value);
  await stop();await start();
  assert.equal((await request('/me',{cookie:a.cookie})).body.user.specialty,changes.specialty);
  assert.equal((await request('/me',{cookie:b.cookie})).body.user.specialty,'Logoped');
  await request('/me',{method:'PATCH',cookie:a.cookie,body:{accent:'plum'}});
  const read=await request('/me',{cookie:a.cookie});assert.equal(read.body.user.phone,changes.phone);assert.equal(read.body.user.accent,'plum');
  for(const body of [{experience_years:81},{accent:'invalid'},{avatar:'data:image/svg+xml;base64,PHN2Zz4='},{avatar:'https://example.com/photo.jpg'},{name:''},{email:'other@example.com'},{id:b.body.user.id}])assert.equal((await request('/me',{method:'PATCH',cookie:a.cookie,body})).status,400);
  assert.equal((await request('/export',{cookie:a.cookie})).body.profile.bio,changes.bio);
});

test('Shared clinic, invitations, therapist conflicts, permissions, revocation and stale writes',async()=>{
 const owner=await request('/auth/register',{method:'POST',body:{name:'Markaz Rahbari',email:'owner@center.test',password:'CenterPassword123'}}),cookie=owner.cookie;
 const invited=await request('/team/invites',{method:'POST',cookie,body:{email:'therapist@center.test'}});assert.equal(invited.status,201);
 assert.equal((await request('/auth/register',{method:'POST',body:{name:'Wrong',email:'wrong@center.test',password:'CenterPassword123',invite:invited.body.code}})).status,400);
 const therapist=await request('/auth/register',{method:'POST',body:{name:'Logoped',email:'therapist@center.test',password:'CenterPassword123',invite:invited.body.code}});assert.equal(therapist.status,200);assert.equal(therapist.body.user.role,'therapist');assert.equal(therapist.body.user.clinic_id,owner.body.user.clinic_id);
 const other=await request('/auth/register',{method:'POST',body:{name:'Other',email:'other@center.test',password:'CenterPassword123'}});
 const p=await request('/patients',{method:'POST',cookie,body:person});assert.equal((await request('/patients',{cookie:therapist.cookie})).body[0].id,p.body.id);assert.equal((await request('/patients',{cookie:other.cookie})).body.length,0);
 assert.equal((await request('/patients/'+p.body.id,{method:'PUT',cookie:therapist.cookie,revision:0,body:{...person,name:'Updated'}})).status,200);
 assert.equal((await request('/patients/'+p.body.id,{method:'PUT',cookie,revision:0,body:person})).status,409);assert.equal((await request('/patients',{cookie})).body[0].name,'Updated');
 const ap={patient_id:p.body.id,therapist_id:owner.body.user.id,date:'2026-12-01',time:'10:00',duration:45,title:'Qabul'};
 assert.equal((await request('/appointments',{method:'POST',cookie,body:ap})).status,201);
 assert.equal((await request('/appointments',{method:'POST',cookie:therapist.cookie,body:{...ap,therapist_id:therapist.body.user.id}})).status,201);
 assert.equal((await request('/appointments',{method:'POST',cookie,body:{...ap,time:'10:30'}})).status,409);
 assert.equal((await request('/appointments',{method:'POST',cookie,body:{...ap,therapist_id:other.body.user.id}})).status,400);
 assert.equal((await request('/patients/'+p.body.id,{method:'DELETE',cookie:therapist.cookie})).status,403);
 assert.equal((await request('/export',{cookie:therapist.cookie})).status,403);
 assert.equal((await request('/team/invites',{method:'POST',cookie:therapist.cookie,body:{email:'no@center.test'}})).status,403);
 assert.equal((await request('/me',{method:'PATCH',cookie:therapist.cookie,body:{clinic:'Hijack'}})).status,403);
 assert.ok((await request('/audit',{cookie})).body.some(r=>r.actor==='Logoped'&&r.action==='update'));
 assert.equal((await request('/team/'+therapist.body.user.id,{method:'PATCH',cookie,body:{disabled:true}})).status,200);
 assert.equal((await request('/me',{cookie:therapist.cookie})).status,401);
 assert.equal((await request('/auth/login',{method:'POST',body:{email:'therapist@center.test',password:'CenterPassword123'}})).status,401);
 assert.equal((await request('/team/'+owner.body.user.id,{method:'PATCH',cookie,body:{disabled:true}})).status,400);
 assert.equal((await request('/team/'+therapist.body.user.id,{method:'PATCH',cookie:other.cookie,body:{disabled:false}})).status,404);
 assert.equal((await request('/team/'+therapist.body.user.id,{method:'PATCH',cookie,body:{disabled:false}})).status,200);
 assert.equal((await request('/auth/login',{method:'POST',body:{email:'therapist@center.test',password:'CenterPassword123'}})).status,200);
});
