import {test,expect} from '@playwright/test';
test('AI draft stays editable and unsaved until logoped review',async({page},testInfo)=>{
 let generates=0;
 await page.route('**/api/ai/status',route=>route.fulfill({json:{configured:true,available:true,demo:false}}));
 await page.route('**/api/ai/exercise-draft',route=>{generates++;expect(route.request().postDataJSON()).toEqual({age:5,sound:'r',goal:'Tovushni eshitib farqlash',duration:5});return route.fulfill({json:{draft:{title:'AI sinov mashqi',category:'Talaffuz',duration:5,instructions:'Logoped tekshiradigan sinov ko‘rsatmasi. Bu haqiqiy Gemini javobi emas.'}}});});
 await page.goto('/#kirish');await page.getByRole('button',{name:'Namuna bilan ko‘rish'}).click();
 if(testInfo.project.name==='mobile')await page.getByRole('button',{name:'Menyuni ochish'}).click();
 await page.locator('nav').getByRole('button',{name:'Mashqlar kutubxonasi'}).click();
 await page.getByRole('button',{name:'AI bilan mashq tayyorlash'}).click();
 await page.getByRole('button',{name:'Mashq loyihasini tayyorlash'}).click();
 const editor=page.getByRole('form',{name:'AI mashq loyihasi'});await expect(editor).toBeVisible();
 expect((await (await page.request.get('/api/exercises')).json()).some(e=>e.title==='AI sinov mashqi')).toBe(false);
 const save=editor.getByRole('button',{name:'Kutubxonaga saqlash'});await expect(save).toBeDisabled();
 await editor.getByRole('checkbox').check();await expect(save).toBeEnabled();
 await editor.getByLabel('Mashq nomi',{exact:true}).fill('Tekshirilgan mashq');await expect(save).toBeDisabled();
 await page.screenshot({path:`artifacts/${testInfo.project.name}-ai-draft.png`,fullPage:true});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await editor.getByRole('checkbox').check();await save.click();await expect(page.getByText('Mashq kutubxonaga saqlandi.',{exact:true})).toBeVisible();
 await expect(page.getByRole('heading',{name:'Tekshirilgan mashq',exact:true})).toBeVisible();expect(generates).toBe(1);
 await page.unroute('**/api/ai/status');
 await page.reload();
 if(testInfo.project.name==='mobile')await page.getByRole('button',{name:'Menyuni ochish'}).click();
 await page.locator('nav').getByRole('button',{name:'Mashqlar kutubxonasi'}).click();
 await page.getByRole('button',{name:'AI bilan mashq tayyorlash'}).click();
 await expect(page.getByText('AI yordamchi shaxsiy logoped hisobida ishlaydi.',{exact:true})).toBeVisible();
 await expect(page.getByRole('button',{name:'Mashq loyihasini tayyorlash'})).toHaveCount(0);
});
