import { test, expect } from '@playwright/test';
test('Logoped can manage a patient, appointment, exercise and result',async({page},testInfo)=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/#kirish');
  await page.getByRole('button',{name:'Namuna bilan ko‘rish'}).click();
  await expect(page.getByRole('heading',{name:'Assalomu alaykum, Aziza.'})).toBeVisible();
  await page.screenshot({path:`artifacts/${testInfo.project.name}-dashboard.png`,fullPage:true});
  await page.getByRole('button',{name:'Bemor qo‘shish Yangi bemor kartasini oching'}).click();
  await page.getByLabel('Bemorning ism va familiyasi').fill('UI Test Bemor');
  await page.getByLabel('Tug‘ilgan sana').fill('2020-05-12');
  await page.getByLabel('Ota-ona / vasiy').fill('UI Test Vasiy');
  await page.getByLabel('Telefon raqami').fill('+998901112233');
  await page.getByLabel('Ishlash yo‘nalishi').fill('R tovushi');
  await page.getByRole('button',{name:'Saqlash',exact:true}).click();
  await expect(page.getByRole('dialog')).not.toBeVisible();
  async function nav(name){if(testInfo.project.name==='mobile')await page.getByRole('button',{name:'Menyuni ochish'}).click();await page.locator('nav').getByRole('button',{name}).click();}
  await nav('Bemorlar');
  await page.getByRole('textbox',{name:'Bemor qidirish'}).fill('UI Test Bemor');
  await page.getByRole('button',{name:'UI Test Bemor',exact:false}).first().click();
  await expect(page.getByRole('heading',{name:'UI Test Bemor',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Qabul belgilash',exact:true}).click();
  await page.getByLabel('Sana *',{exact:true}).fill('2026-10-20');
  await page.getByLabel('Vaqt (Toshkent)').fill('15:00');
  await page.getByRole('button',{name:'Saqlash',exact:true}).click();
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await page.getByRole('button',{name:'Natija qo‘shish',exact:true}).click();
  await page.getByLabel('Baho (0–100%)').fill('85');
  await page.getByLabel('Kuzatuv va keyingi qadamlar').fill('UI test natijasi');
  await page.getByRole('button',{name:'Saqlash',exact:true}).click();
  await expect(page.getByText('UI test natijasi')).toBeVisible();
  await page.screenshot({path:`artifacts/${testInfo.project.name}-patient.png`,fullPage:true});
  // A second score on the same day must become the latest score.
  await page.getByRole('button',{name:'Natija qo‘shish',exact:true}).click();
  await page.getByLabel('Baho (0–100%)').fill('90');
  await page.getByRole('button',{name:'Saqlash',exact:true}).click();
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await nav('Mashqlar kutubxonasi');
  await page.getByRole('button',{name:'Mashq yaratish',exact:true}).click();
  await page.getByLabel('Mashq nomi').fill('UI Test Mashq');
  await page.getByLabel('Bajarish tartibi').fill('Mutaxassis belgilagan mashq tartibi.');
  await page.getByRole('button',{name:'Saqlash',exact:true}).click();
  await expect(page.getByRole('heading',{name:'UI Test Mashq',exact:true})).toBeVisible();
  await nav('Qabul jadvali');
  await page.getByLabel('Qabul sanasi').fill('2026-10-20');
  await expect(page.getByRole('button',{name:'UI Test Bemor',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'UI Test Bemor qabulini yakunlash',exact:true}).click();
  await expect(page.locator('.appointment .badge')).toHaveText('Yakunlangan');
  await page.reload();
  await expect(page.getByRole('heading',{name:'Assalomu alaykum, Aziza.'})).toBeVisible();
  await nav('Bemorlar');await page.getByRole('textbox',{name:'Bemor qidirish'}).fill('UI Test Bemor');
  await expect(page.getByRole('button',{name:'UI Test Bemor',exact:false}).first()).toBeVisible();
  await expect(page.locator('tbody .score-pill')).toHaveText('90%');
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});
