import {test,expect} from '@playwright/test';
test('Patient profile keeps result ownership and schedule uses patient rows',async({page},info)=>{
 const suffix=Date.now()+'-'+info.project.name;
 await page.goto('/');await expect(page.locator('.room-background')).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.screenshot({path:'artifacts/'+info.project.name+'-room-home.png',fullPage:true});
 const staff=await page.request.post('/api/auth/register',{headers:{'X-Requested-With':'Nutq'},data:{name:'Iroda Test',email:'feature-'+suffix+'@example.test',password:'FeaturePassword123'}});expect(staff.status()).toBe(200);
 const p=await page.request.post('/api/patients',{headers:{'X-Requested-With':'Nutq'},data:{name:'Ali Valiyev',birth_date:'2020-01-01',telegram:'',focus:'R tovushi'}});const patient=await p.json();
 const other=await page.request.post('/api/patients',{headers:{'X-Requested-With':'Nutq'},data:{name:'Malika Karimova',birth_date:'2019-01-01',telegram:'@other_parent',focus:'Lug‘at'}});expect(other.status()).toBe(201);
 await page.goto('/#kirish');await page.reload();await expect(page.getByRole('heading',{name:'Assalomu alaykum, Iroda.'})).toBeVisible();
 if(info.project.name==='mobile')await page.getByRole('button',{name:'Menyuni ochish'}).click();
 await page.locator('nav').getByRole('button',{name:/Bemorlar/}).click();await page.getByRole('button',{name:/Ali Valiyev/}).first().click();
 await expect(page.getByRole('heading',{name:'Bemor videolari'})).toBeVisible();
 await page.getByRole('button',{name:'Natija qo‘shish',exact:true}).click();
 await expect(page.getByRole('dialog').locator('.fixed-patient')).toContainText('Ali Valiyev');
 await expect(page.getByRole('dialog').getByRole('combobox',{name:/Bemor/})).toHaveCount(0);
 await page.getByLabel('Baho (0–100%)').fill('75');await page.getByRole('button',{name:'Saqlash',exact:true}).click();
 await expect(page.getByRole('dialog')).toHaveCount(0);
 const results=await (await page.request.get('/api/results')).json();expect(results[0].patient_id).toBe(patient.id);
 await expect(page.getByRole('button',{name:'Telegram ulash havolasi',exact:true})).toBeDisabled();
 await page.getByRole('button',{name:'Kartani tahrirlash'}).click();
 await expect(page.getByRole('dialog').getByLabel(/Telegram username/)).toHaveCount(0);
 await page.getByLabel('Telefon raqami').fill('+998 90 123 45 67');
 await page.getByRole('dialog').getByRole('button',{name:'Saqlash',exact:true}).click();
 await expect(page.getByRole('dialog')).toHaveCount(0);
 await expect(page.locator('.telegram-connection')).toContainText('+998901234567',{timeout:10000});
 await page.getByRole('button',{name:'Telegram ulash havolasi',exact:true}).click();await expect(page.getByLabel('Bemor uchun Telegram ulash havolasi')).toHaveValue(/https:\/\/t.me\/nutq_test_bot\?start=/);await expect(page.locator('.telegram-link')).toContainText('Telefon raqamni ulashish');
 await page.getByLabel('Video nomi').fill('Uyda talaffuz mashqi');await page.locator('input[type=file]').setInputFiles({name:'exercise.mp4',mimeType:'video/mp4',buffer:Buffer.from('000000186674797069736f6d0000000069736f6d6d703432','hex')});
 await page.getByRole('button',{name:'Videoni saqlash',exact:true}).click();await expect(page.getByText('Telegram ulanishini kutmoqda',{exact:true})).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'artifacts/'+info.project.name+'-patient-video.png',fullPage:true});
 if(info.project.name==='mobile')await page.getByRole('button',{name:'Menyuni ochish'}).click();
 await page.locator('nav').getByRole('button',{name:'Qabul jadvali'}).click();
 await page.getByLabel('Taqvim ko‘rinishi').selectOption('patients');
 await expect(page.locator('.schedule-person').filter({hasText:'Ali Valiyev'})).toBeVisible();
 await page.getByRole('button',{name:'Ali Valiyev uchun 09:00 da qabul belgilash',exact:true}).click();
 await expect(page.getByRole('dialog').locator('.fixed-patient')).toContainText('Ali Valiyev');await expect(page.getByLabel('Vaqt (Toshkent)')).toHaveValue('09:00');
 await page.getByRole('button',{name:'Saqlash',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);
 await expect(page.locator('.schedule-booking')).toContainText('09:00');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'artifacts/'+info.project.name+'-patient-schedule.png',fullPage:true});
 await page.getByRole('button',{name:'Och mavzuga o‘tish'}).click();await page.screenshot({path:'artifacts/'+info.project.name+'-patient-schedule-light.png',fullPage:true});
});
