import {createApp} from './app.js';
import {backupManager} from './backups.js';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const filename=path.resolve(process.env.DATABASE_PATH||path.join(root,'data','nutq.sqlite'));
const {app,db}=createApp({filename});
const backups=backupManager(db,process.env.BACKUP_DIRECTORY||path.join(path.dirname(filename),'backups'));
app.locals.backups=backups;
const port=Number(process.env.PORT||3001);
const server=app.listen(port,process.env.HOST||'0.0.0.0',()=>{console.log(`Nutq: http://localhost:${port}`);backups.start();});
server.on('error',error=>{console.error(error.code==='EADDRINUSE'?'Bu port band. Nutq serveri allaqachon ishlayotgan bo‘lishi mumkin.':error.message);db.close();process.exitCode=1;});
for(const signal of ['SIGINT','SIGTERM'])process.on(signal,()=>server.close(async()=>{await backups.stop();db.close();process.exit(0);}));
