-- Kept in an isolated schema selected by DATABASE_SCHEMA; public tables are never altered.
CREATE TABLE IF NOT EXISTS schema_migrations(version integer PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS users (
 id text PRIMARY KEY, name text NOT NULL, email text NOT NULL UNIQUE, password text NOT NULL,
 clinic text NOT NULL DEFAULT 'Mening amaliyotim', demo integer NOT NULL DEFAULT 0 CHECK(demo IN (0,1)),
 created_at text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC','YYYY-MM-DD HH24:MI:SS'),
 specialty text NOT NULL DEFAULT 'Logoped', phone text NOT NULL DEFAULT '',address text NOT NULL DEFAULT '',bio text NOT NULL DEFAULT '',
 experience_years integer CHECK(experience_years BETWEEN 0 AND 80),accent text NOT NULL DEFAULT 'green',avatar text NOT NULL DEFAULT '',
 clinic_id text,role text NOT NULL DEFAULT 'admin',disabled integer NOT NULL DEFAULT 0 CHECK(disabled IN (0,1)),revision integer NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS clinics(id text PRIMARY KEY,owner_id text NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,name text NOT NULL);
CREATE TABLE IF NOT EXISTS sessions(token text PRIMARY KEY,user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,expires bigint NOT NULL);
CREATE INDEX IF NOT EXISTS sessions_expiry ON sessions(expires);
CREATE TABLE IF NOT EXISTS patients(
 id text PRIMARY KEY,user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 name text NOT NULL,birth_date text NOT NULL,guardian text NOT NULL DEFAULT '',phone text NOT NULL DEFAULT '',focus text NOT NULL DEFAULT '',notes text NOT NULL DEFAULT '',status text NOT NULL DEFAULT 'active' CHECK(status IN ('active','archived')),
 created_at text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC','YYYY-MM-DD HH24:MI:SS'),
 revision integer NOT NULL DEFAULT 0,updated_by text,created_order bigint GENERATED ALWAYS AS IDENTITY, UNIQUE(id,user_id)
);
CREATE TABLE IF NOT EXISTS exercises(
 id text PRIMARY KEY,user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,title text NOT NULL,category text NOT NULL,duration integer NOT NULL CHECK(duration BETWEEN 1 AND 120),instructions text NOT NULL,
 created_at text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC','YYYY-MM-DD HH24:MI:SS'),revision integer NOT NULL DEFAULT 0,updated_by text,created_order bigint GENERATED ALWAYS AS IDENTITY
);
CREATE TABLE IF NOT EXISTS appointments(
 id text PRIMARY KEY,user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,patient_id text NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
 date text NOT NULL,time text NOT NULL,duration integer NOT NULL CHECK(duration BETWEEN 5 AND 240),title text NOT NULL,status text NOT NULL DEFAULT 'scheduled' CHECK(status IN ('scheduled','completed','cancelled')),notes text NOT NULL DEFAULT '',
 revision integer NOT NULL DEFAULT 0,updated_by text,therapist_id text NOT NULL REFERENCES users(id),created_order bigint GENERATED ALWAYS AS IDENTITY,
 FOREIGN KEY(patient_id,user_id) REFERENCES patients(id,user_id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS results(
 id text PRIMARY KEY,user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,patient_id text NOT NULL REFERENCES patients(id) ON DELETE CASCADE,exercise_id text REFERENCES exercises(id) ON DELETE SET NULL,
 date text NOT NULL,score integer NOT NULL CHECK(score BETWEEN 0 AND 100),notes text NOT NULL DEFAULT '',
 created_at text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC','YYYY-MM-DD HH24:MI:SS'),revision integer NOT NULL DEFAULT 0,updated_by text,created_order bigint GENERATED ALWAYS AS IDENTITY,
 FOREIGN KEY(patient_id,user_id) REFERENCES patients(id,user_id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS invitations(token text PRIMARY KEY,clinic_id text NOT NULL REFERENCES clinics(id) ON DELETE CASCADE,email text NOT NULL,expires bigint NOT NULL,created_by text NOT NULL REFERENCES users(id));
CREATE TABLE IF NOT EXISTS audit_log(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,clinic_id text NOT NULL,actor_id text NOT NULL,action text NOT NULL,record_type text NOT NULL,record_id text NOT NULL,created_at text NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC','YYYY-MM-DD HH24:MI:SS'));
CREATE INDEX IF NOT EXISTS users_clinic ON users(clinic_id);
CREATE INDEX IF NOT EXISTS patients_owner ON patients(user_id);
CREATE INDEX IF NOT EXISTS appointments_owner_date ON appointments(user_id,date);
CREATE INDEX IF NOT EXISTS appointments_therapist_date ON appointments(therapist_id,date);
CREATE INDEX IF NOT EXISTS results_owner_patient ON results(user_id,patient_id,date);
CREATE INDEX IF NOT EXISTS exercises_owner ON exercises(user_id);
CREATE INDEX IF NOT EXISTS audit_clinic ON audit_log(clinic_id,id);
