import {useEffect,useState} from 'react';
import {IconArrowRight,IconLogout,IconRefresh,IconTrash} from '@tabler/icons-react';
import {api} from './api';
import {ThemeSwitch} from './controls';
import {PublicBrand} from './landing';
import type {User} from './profile';

type Assigned={id:string;exercise_id:string;note:string;title:string;duration:number;instructions:string};
type Account={id:string;email:string;disabled:number};
type Access={account:Account|null;exercises:Assigned[]};
export function ClientAccess({patientId,exercises,demo}:{patientId:string;exercises:{id:string;title:string}[];demo:boolean}){
 const [data,setData]=useState<Access|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[showPassword,setShowPassword]=useState(false);
 async function reload(){setData(await api<Access>('/patients/'+patientId+'/access'));}
 useEffect(()=>{let active=true;setData(null);setError('');setMessage('');api<Access>('/patients/'+patientId+'/access').then(v=>{if(active)setData(v)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false};},[patientId]);
 async function mutate(path:string,method:string,body?:unknown){setBusy(true);setError('');setMessage('');try{await api('/patients/'+patientId+path,{method,body:body?JSON.stringify(body):undefined});setMessage('O‘zgarishlar saqlandi.');try{await reload();}catch{setError('Saqlandi, lekin holat yangilanmadi. Yangilash tugmasini bosing.');}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="panel client-access"><h2>Klient kabineti</h2><p className="muted">Bemor yoki ota-ona uchun akkaunt yarating. U o‘z qabullari, biriktirilgan mashqlari va natijalarini ko‘radi. Karta va qabuldagi ichki izohlar ko‘rsatilmaydi.</p>
 {error&&<p className="error" role="alert">{error}</p>}{message&&<p className="access-success" role="status">{message}</p>}
 {!data?<button className="button secondary" onClick={()=>reload().catch(e=>setError(e.message))}>Holatni yangilash</button>:<>
 {data.account?<><div className="client-account-details"><strong>Login: {data.account.email}</strong><p className={'badge '+(data.account.disabled?'cancelled':'completed')}>{data.account.disabled?'Kirish yopilgan':'Akkaunt faol'}</p></div><p className="hint">Klient saytning «Kabinetga kirish» tugmasi orqali kiradi.</p><div className="access-actions"><button className="button secondary" disabled={busy} onClick={()=>void mutate('/access','PATCH',{disabled:!data.account!.disabled})}>{data.account.disabled?'Kirishni yoqish':'Kirishni yopish'}</button><button className="text-button" disabled={busy} onClick={()=>reload().catch(e=>setError(e.message))}>Yangilash</button></div><details className="client-reset"><summary>Klient parolini yangilash</summary><form onSubmit={e=>{e.preventDefault();void mutate('/access','PATCH',{password:new FormData(e.currentTarget).get('password')});}}><label className="field"><span>Klient uchun yangi parol</span><input name="password" type="password" required minLength={10} maxLength={128} autoComplete="new-password" placeholder="Kamida 10 ta belgi"/></label><button className="button secondary" disabled={busy}>Klient parolini yangilash</button><p className="hint">Parol yangilanganda klientning avvalgi kirishlari yopiladi.</p></form></details></>:
 demo?<p className="hint">Klient akkaunti yaratish uchun logopedning shaxsiy hisobiga kiring.</p>:<form onSubmit={e=>{e.preventDefault();void mutate('/access','POST',Object.fromEntries(new FormData(e.currentTarget)));}}><label className="field"><span>Klient emaili</span><input type="email" name="email" required maxLength={200} autoComplete="off" placeholder="otaona@example.com"/></label><label className="field"><span>Klient paroli</span><input type={showPassword?'text':'password'} name="password" required minLength={10} maxLength={128} autoComplete="new-password" placeholder="Kamida 10 ta belgi"/></label><label className="hint"><input type="checkbox" checked={showPassword} onChange={e=>setShowPassword(e.target.checked)}/> Parolni ko‘rsatish</label><div className="access-actions"><button className="button primary" disabled={busy}>{busy?'Saqlanmoqda…':'Klient akkaunti yaratish'}</button></div><p className="hint">Email va parolni klientga o‘zingiz yetkazing. Xabar avtomatik yuborilmaydi.</p></form>}
 <hr/><h3>Klientga biriktirilgan mashqlar</h3>{data.exercises.length?data.exercises.map(e=><div className="access-item" key={e.id}><div><strong>{e.title}</strong><small>{e.duration} daqiqa</small>{e.note&&<p>{e.note}</p>}</div><button className="icon-button" disabled={busy} aria-label={e.title+' biriktirmasini olib tashlash'} onClick={()=>void mutate('/exercises/'+e.id,'DELETE')}><IconTrash size={18}/></button></div>):<p className="muted">Hali mashq biriktirilmagan.</p>}
 <form onSubmit={e=>{e.preventDefault();void mutate('/exercises','POST',Object.fromEntries(new FormData(e.currentTarget)));}}><label className="field"><span>Klient uchun mashq</span><select name="exercise_id" required defaultValue=""><option value="" disabled>Mashqni tanlang</option>{exercises.filter(e=>!data.exercises.some(a=>a.exercise_id===e.id)).map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select></label><label className="field"><span>Klientga ko‘rsatma</span><textarea name="note" maxLength={2000} rows={3} placeholder="Qanday va qachon bajarish kerak?"/></label><button className="button secondary" disabled={busy||!exercises.some(e=>!data.exercises.some(a=>a.exercise_id===e.id))}>Mashqni biriktirish</button>{!exercises.length&&<p className="hint">Avval mashqlar kutubxonasiga mashq qo‘shing.</p>}</form>
 </>}</section>;
}
type Overview={patient:{name:string};exercises:Assigned[];appointments:{id:string;date:string;time:string;duration:number;title:string;status:string}[];results:{id:string;date:string;score:number;notes:string;exercise_title:string|null}[]};
const status:Record<string,string>={scheduled:'Rejada',completed:'Yakunlangan',cancelled:'Bekor qilingan'};
const date=(s:string)=>s.split('-').reverse().join('.');
export function ClientPortal({user,onLogout}:{user:User;onLogout:()=>void}){
 const [data,setData]=useState<Overview|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[passwordMessage,setPasswordMessage]=useState('');
 async function load(){setBusy(true);try{setData(await api<Overview>('/client/overview'));setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{let active=true;async function refresh(){try{const v=await api<Overview>('/client/overview');if(active){setData(v);setError('');}}catch(e){if(active)setError((e as Error).message);}}void refresh();const timer=setInterval(()=>void refresh(),30000);return()=>{active=false;clearInterval(timer)};},[]);
 async function logout(){setBusy(true);try{await api('/logout',{method:'POST'});onLogout();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="client-portal"><header><PublicBrand/><div><ThemeSwitch/><button className="button secondary" disabled={busy} onClick={()=>void logout()}><IconLogout size={17}/>Chiqish</button></div></header><div className="portal-heading"><span className="eyebrow">MENING KABINETIM</span><h1>Salom, {user.name.split(' ')[0]}.</h1><p>{data?.patient.name||'Sizning'} mashg‘ulotlari, mashqlari va natijalari.</p><div className="client-refresh"><button className="text-button" disabled={busy} onClick={()=>void load()}><IconRefresh size={16}/>Yangilash</button><a className="text-button" href="https://t.me/Defektolog_Iroda" target="_blank" rel="noreferrer">Logopedga yozish <IconArrowRight size={16}/></a></div></div>
 {error&&<p className="error" role="alert">{error}</p>}{!data&&!error&&<p role="status">Kabinet yuklanmoqda…</p>}{data&&<div className="portal-grid"><div><section className="panel"><h2>Mening mashqlarim</h2><p className="muted">Logoped siz uchun tanlagan mashqlar.</p>{!data.exercises.length&&<p>Logoped hali mashq biriktirmagan.</p>}{data.exercises.map(e=><article className="portal-item" key={e.id}><strong>{e.title}</strong><span className="badge">{e.duration} daqiqa</span><p>{e.instructions}</p>{e.note&&<div><small>Logoped ko‘rsatmasi</small><p>{e.note}</p></div>}</article>)}</section><section className="panel"><h2>Mening natijalarim</h2><p className="hint">Baholar va kuzatuvlarni logoped kiritadi.</p>{!data.results.length&&<p>Hali natija qayd etilmagan.</p>}{data.results.map(r=><article className="portal-item" key={r.id}><div className="portal-meta"><span className="score-pill">{r.score}%</span><span>{date(r.date)}</span></div><h3>{r.exercise_title||'Umumiy kuzatuv'}</h3>{r.notes&&<p>{r.notes}</p>}</article>)}</section></div><div><section className="panel"><h2>Mening qabullarim</h2><p className="hint">Vaqtlar Toshkent vaqti bilan.</p>{!data.appointments.length&&<p>Hali qabul belgilanmagan. Vaqtni logoped bilan kelishing.</p>}{data.appointments.map(a=><article className="portal-item" key={a.id}><strong>{a.title}</strong><p>{date(a.date)} · {a.time} · {a.duration} daqiqa</p><span className={'badge '+a.status}>{status[a.status]}</span></article>)}</section><section className="panel client-password"><h2>Parolimni o‘zgartirish</h2><p className="hint">Login: {user.email}</p><form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;setBusy(true);setPasswordMessage('');try{await api('/password',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(form)))});form.reset();setPasswordMessage('Parolingiz yangilandi.');}catch(e){setPasswordMessage((e as Error).message);}finally{setBusy(false);}}}><label className="field"><span>Amaldagi parol</span><input name="current" type="password" required maxLength={128} autoComplete="current-password"/></label><label className="field"><span>Yangi parol</span><input name="password" type="password" required minLength={10} maxLength={128} autoComplete="new-password"/></label><button className="button secondary" disabled={busy}>Parolni yangilash</button>{passwordMessage&&<p role="status">{passwordMessage}</p>}</form></section></div></div>}</div>;
}
