import {useEffect,useId,useRef,useState} from 'react';
import {IconCheck,IconChevronDown,IconSearch,IconSun,IconMoon} from '@tabler/icons-react';
export function ThemeSwitch(){
 const [theme,setTheme]=useState(()=>{try{return localStorage.getItem('nutq-theme')==='light'?'light':'dark'}catch{return 'dark'}});
 useEffect(()=>{document.documentElement.dataset.theme=theme;try{localStorage.setItem('nutq-theme',theme)}catch{}},[theme]);
 return <button type="button" className="theme-switch" aria-label={theme==='dark'?'Och mavzuga o‘tish':'To‘q mavzuga o‘tish'} title={theme==='dark'?'Och mavzu':'To‘q mavzu'} onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?<IconSun size={21}/>:<IconMoon size={21}/>}</button>;
}
export function PatientSelect({patients,defaultValue}:{patients:{id:string;name:string;status:string;focus:string}[];defaultValue:string}){
 const [value,setValue]=useState(defaultValue),[open,setOpen]=useState(false),[query,setQuery]=useState(''),[active,setActive]=useState(0);
 const root=useRef<HTMLDivElement>(null),input=useRef<HTMLInputElement>(null),trigger=useRef<HTMLButtonElement>(null),id=useId();
 const selected=patients.find(p=>p.id===value),filtered=patients.filter(p=>(p.name+' '+p.focus).toLocaleLowerCase().includes(query.toLocaleLowerCase()));
 useEffect(()=>{if(open){input.current?.focus();const close=(e:PointerEvent)=>{if(!root.current?.contains(e.target as Node))setOpen(false)};document.addEventListener('pointerdown',close);return()=>document.removeEventListener('pointerdown',close)}},[open]);
 useEffect(()=>{document.getElementById(id+'-'+active)?.scrollIntoView({block:'nearest'})},[active,id]);
 function choose(patient:typeof patients[number]){setValue(patient.id);setOpen(false);setQuery('');trigger.current?.focus()}
 return <div className="field patient-picker" ref={root} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))setOpen(false)}}><span id={id+'-label'}>Bemor *</span><input className="picker-validation" tabIndex={-1} aria-label="Tanlangan bemor" name="patient_id" value={value} required onChange={()=>{}} onInvalid={e=>{e.preventDefault();setOpen(true)}}/><button ref={trigger} type="button" className="picker-trigger" aria-labelledby={id+'-label'} aria-haspopup="listbox" aria-expanded={open} aria-controls={id} onClick={()=>{setOpen(!open);setQuery('');setActive(0)}} onKeyDown={e=>{if(e.key==='ArrowDown'){e.preventDefault();setOpen(true);setActive(0)}}}><span className={selected?'':'muted'}>{selected?.name||'Bemorni tanlang'}</span><IconChevronDown size={18}/></button>{open&&<div className="picker-menu"><div className="picker-search"><IconSearch size={18}/><input ref={input} role="combobox" aria-label="Ro‘yxatdan bemor qidirish" aria-expanded="true" aria-controls={id} aria-autocomplete="list" aria-activedescendant={filtered[active]?id+'-'+active:undefined} placeholder="Ism yoki yo‘nalish bo‘yicha qidirish" value={query} onChange={e=>{setQuery(e.target.value);setActive(0)}} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();setOpen(false);trigger.current?.focus()}if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();setActive(n=>Math.max(0,Math.min(filtered.length-1,n+(e.key==='ArrowDown'?1:-1))))}if(e.key==='Enter'){e.preventDefault();if(filtered[active])choose(filtered[active])}}}/></div><div role="listbox" id={id} aria-labelledby={id+'-label'} className="picker-options">{filtered.map((p,i)=><button type="button" role="option" aria-selected={value===p.id} id={id+'-'+i} key={p.id} className={'picker-option '+(i===active?'highlighted':'')} onMouseDown={e=>e.preventDefault()} onClick={()=>choose(p)}><span className="picker-avatar">{p.name.split(' ').slice(0,2).map(n=>n[0]).join('')}</span><span><strong>{p.name}</strong><small>{p.status==='archived'?'Arxiv · ':''}{p.focus||'Yo‘nalish belgilanmagan'}</small></span>{value===p.id&&<IconCheck size={18}/>}</button>)}{!filtered.length&&<p className="picker-empty">{patients.length?'Bemor topilmadi. Boshqa ism yozib ko‘ring.':'Avval Bemorlar bo‘limidan bemor qo‘shing.'}</p>}</div><div className="picker-caption">{filtered.length} ta bemor</div></div>}</div>
}
