import {useEffect,useState} from 'react';
import {IconBook2,IconExternalLink,IconCheck,IconPlus} from '@tabler/icons-react';
import {api} from './api';
type Item={id:string;title:string;category:string;duration:number;audience:string;materials:string;instructions:string;source:{name:string;url:string};imported:boolean};
export function ExerciseCatalog({search,category,onImported}:{search:string;category:string;onImported:()=>Promise<void>}){
 const [items,setItems]=useState<Item[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState('');
 useEffect(()=>{void api<Item[]>('/exercise-catalog').then(setItems).catch(e=>setError(e.message));},[]);
 async function add(item:Item){setBusy(item.id);setError('');try{await api('/exercise-catalog/'+item.id+'/import',{method:'POST'});setItems(rows=>rows.map(e=>e.id===item.id?{...e,imported:true}:e));await onImported();}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 const visible=items.filter(e=>(category==='Barchasi'||e.category===category)&&e.title.toLocaleLowerCase().includes(search.toLocaleLowerCase()));
 return <section className="catalog-section"><div className="section-heading"><div><h2>Manbali mashqlar <span className="count">{items.length}</span></h2><p>NHS va ASHA tavsiyalarining qisqa o‘zbekcha bayoni. Logoped bemorga moslab tanlaydi.</p></div></div><p className="muted">Davomiyliklar reja uchun tavsiya etilgan boshlang‘ich qiymat. Kutubxonaga qo‘shgach, maqsad, so‘zlar va vaqtni tahrirlang.</p>{error&&<p className="error" role="alert">{error}</p>}<div className="exercise-grid">{visible.map(e=><article className="panel exercise-card" key={e.id}><div className="exercise-top"><span className="exercise-symbol"><IconBook2 size={26}/></span><span className="badge">{e.category}</span></div><h3>{e.title}</h3><p className="muted">{e.audience}</p><p>{e.instructions}</p><p className="muted">Jihozlar: {e.materials}.</p><a className="text-button catalog-source" href={e.source.url} target="_blank" rel="noreferrer">{e.source.name} <IconExternalLink size={15}/></a><div className="exercise-footer"><span>{e.duration} daqiqalik reja</span><button className="button secondary" disabled={!!busy||e.imported} onClick={()=>void add(e)}>{e.imported?<><IconCheck size={16}/>Qo‘shilgan</>:<><IconPlus size={16}/>{busy===e.id?'Saqlanmoqda…':'Qo‘shish'}</>}</button></div></article>)}</div></section>;
}
